[package]
name = "lexify-api"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "lexify-api"

[dependencies]
dotenvy = "0.15.6"
serde = "1.0.138"
serde_json = "1.0.82"
futures = "0.3.21"
tracing = "0.1.36"
rocket_firebase_auth = "0.2.3"
rocket_cors = { git = "https://github.com/lawliet89/rocket_cors", rev = "54fae0701dffbe5df686465780218644ee3fae5f" }
diesel = { version = "2.0.0-rc.1", features = ["r2d2", "mysql", "chrono"] }
chrono = { version = "0.4", features = ["serde"] }
rocket = { version = "0.5.0-rc.1", features = ["json"] }

[dev-dependencies]
tokio = "1.19.2"
bincode = "1.3.3"
wiremock = "0.5.14"
once_cell = "1.15.0"
rocket_firebase_auth = { version = "0.2.2", features = ["env", "encode"] }
