version: '3'

services:
  db:
    image: mysql:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: lexify
      MYSQL_USR: root
