version: '3'

services:
  db:
    image: mysql:8
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql/data
    ports:
      - "5432:5432"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DB: lexify

volumes:
  db: null
