BEGIN;

ALTER TABLE users
MODIFY COLUMN id VARCHAR(255);

ALTER TABLE collections
MODIFY COLUMN id VARCHAR(255),
MODIFY COLUMN user_id VARCHAR(255);

ALTER TABLE vocab_words
MODIFY COLUMN id VARCHAR(255),
MODIFY COLUMN collection_id VARCHAR(255);

COMMIT;