BEGIN;

ALTER TABLE collections
MODIFY COLUMN id VARCHAR(255);

ALTER TABLE vocab_words
MODIFY COLUMN collection_id VARCHAR(255),
MODIFY COLUMN fails INT DEFAULT 0,
MODIFY COLUMN successes INT DEFAULT 0;

COMMIT;