BEGIN;

ALTER TABLE collections
MODIFY COLUMN user_id VARCHAR(255) NOT NULL;

ALTER TABLE vocab_words
MODIFY COLUMN collection_id VARCHAR(255) NOT NULL,
MODIFY COLUMN fails INT NOT NULL DEFAULT 0,
MODIFY COLUMN successes INT NOT NULL DEFAULT 0;

COMMIT;
